name: Consistent Pull Request

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  consistent-pull-request:
    name: Consistent Pull Request
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Check pr label name
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          rules: |
            main <- feature/* [feature]
            main <- bugfix/* [bugfix]
            main <- refactor/* [refactor]
            main <- chore/* [chore]
            main <- deps/* [deps]

      - name: Check head branch name
        uses: agaroot-technologies/action-restrict-head-branch@48b7777bbd99e4702abe38e4a996fcd5a2453667 # v1.0.0
        with:
          rules: |
            feature/* bugfix/* refactor/* chore/* deps/*

      - name: Check base branch name
        uses: agaroot-technologies/action-restrict-base-branch@b0773c065df5ad61012ee1802d7571c3624001c6 # v1.0.1
        with:
          rules: |
            main <- feature/* bugfix/* refactor/* chore/* deps/*
